import { useState } from 'react'
import './App.css'
import './Extra.css'

type Base = 1 | 2 | 3
type Player = { id: string; last: string; first: string; pos: string; avg: string }
type Team = { name: string; players: Player[]; bench: Player[] }
const positions = ['投', '捕', '一', '二', '三', '遊', '左', '中', '右', '打']
const fieldSlots = ['左', '中', '右', '三', '遊', '二', '一', '投', '捕']
const awayPlayers: Player[] = [['田中','太郎','遊','.325'],['佐藤','健','左','.286'],['鈴木','蓮','三','.301'],['高橋','陸','一','.278'],['伊藤','翔','中','.250'],['山本','悠','右','.265'],['木村','陽','二','.241'],['吉田','大輝','捕','.289'],['清水','亮','投','.310']].map(([last,first,pos,avg],i)=>({id:`a${i}`,last,first,pos,avg}))
const homePlayers: Player[] = [['渡辺','優','左','.294'],['小林','海斗','中','.276'],['加藤','航','右','.303'],['中村','龍','三','.251'],['森','拓也','遊','.285'],['石井','駿','二','.267'],['井上','直人','一','.312'],['山田','誠','投','.220'],['岡田','蒼','捕','.258']].map(([last,first,pos,avg],i)=>({id:`h${i}`,last,first,pos,avg}))
const bench: Player[] = [['斎藤','颯','打','.273'],['松本','晴','打','.238'],['藤田','力','打','.251']].map(([last,first,pos,avg],i)=>({id:`b${i}`,last,first,pos,avg}))
const copy = (players: Player[]) => players.map(p=>({...p}))

function Avatar({name,small=false}:{name:string;small?:boolean}) { return <span className={`avatar ${small?'small':''}`}>{name.slice(0,1)}</span> }
function App() {
  const [inning,setInning]=useState(3), [half,setHalf]=useState<'表'|'裏'>('表'), [balls,setBalls]=useState(2), [strikes,setStrikes]=useState(1), [outs,setOuts]=useState(1), [batterIndex,setBatterIndex]=useState(0), [awayScore,setAwayScore]=useState(3), [homeScore,setHomeScore]=useState(1)
  const [innings,setInnings]=useState<{away:(number|null)[];home:(number|null)[]}>({away:[1,0,2,null,null],home:[0,1,0,null,null]})
  const [runners,setRunners]=useState<Partial<Record<Base,string>>>({1:'佐藤',2:'鈴木'}), [lastResult,setLastResult]=useState(''), [plays,setPlays]=useState(['3回表 佐藤 四球','3回表 田中 ヒット','2回裏 山田 三振','2回表 鈴木 ホームラン'])
  const [away,setAway]=useState<Team>({name:'多摩リバース',players:copy(awayPlayers),bench:copy(bench)}), [home,setHome]=useState<Team>({name:'府中フェニックス',players:copy(homePlayers),bench:copy(bench).map(p=>({...p,id:`hb${p.id}`}))})
  const [admin,setAdmin]=useState(false), [askPassword,setAskPassword]=useState(false), [password,setPassword]=useState(''), [passwordError,setPasswordError]=useState(false), [resultType,setResultType]=useState<string|null>(null), [drag,setDrag]=useState<{team:'away'|'home'; area:'lineup'|'bench'; index:number}|null>(null)
  const batter=away.players[batterIndex%away.players.length]; const pitcher=home.players.find(p=>p.pos==='投')??home.players[7]
  const resetCount=()=>{setBalls(0);setStrikes(0)}; const nextBatter=()=>setBatterIndex(i=>(i+1)%away.players.length)
  const addPlay=(result:string)=>{setLastResult(result);setPlays(list=>[`${inning}回${half} ${batter.last} ${result}`,...list].slice(0,10))}
  const scoreRuns=(runs:number)=>{if(!runs)return; if(half==='表')setAwayScore(v=>v+runs);else setHomeScore(v=>v+runs); setInnings(current=>{const key=half==='表'?'away':'home', scores=[...current[key]];scores[inning-1]=(scores[inning-1]??0)+runs;return {...current,[key]:scores}})}
  const changeSide=()=>{if(half==='裏')setInning(v=>v+1);setHalf(v=>v==='表'?'裏':'表');setOuts(0);resetCount();setRunners({});setLastResult('')}
  const recordOut=(result:string)=>{addPlay(result);resetCount();nextBatter();if(outs===2)changeSide();else setOuts(v=>v+1)}
  const advanceHit=(bases:number,result:string)=>{const next:Partial<Record<Base,string>>={};let runs=0;([3,2,1]as Base[]).forEach(base=>{const runner=runners[base];if(!runner)return;if(base+bases>3)runs++;else next[(base+bases)as Base]=runner});if(bases===4)runs++;else next[bases as Base]=batter.last;scoreRuns(runs);setRunners(next);addPlay(result);resetCount();nextBatter();setResultType(null)}
  const walk=()=>{const next={...runners};let runs=0;if(next[1]){if(next[2]){if(next[3])runs=1;next[3]=next[2]}next[2]=next[1]}next[1]=batter.last;scoreRuns(runs);setRunners(next);addPlay('四球');resetCount();nextBatter();setResultType(null)}
  const pitch=(type:'ball'|'strike'|'foul')=>{if(type==='ball'){if(balls===3)walk();else setBalls(v=>v+1);return}if(type==='foul'&&strikes===2)return;if(strikes===2)recordOut('三振');else setStrikes(v=>v+1)}
  const submitPassword=()=>{if(password==='1234'){setAdmin(true);setAskPassword(false);setPassword('');setPasswordError(false)}else setPasswordError(true)}
  const getTeam=(which:'away'|'home')=>which==='away'?away:home; const updateTeam=(which:'away'|'home',team:Team)=>which==='away'?setAway(team):setHome(team)
  const movePlayer=(toTeam:'away'|'home',toArea:'lineup'|'bench',toIndex:number)=>{if(!drag)return;const from=getTeam(drag.team),to=getTeam(toTeam);const fromList=[...from[drag.area==='lineup'?'players':'bench']], [item]=fromList.splice(drag.index,1);const target=drag.team===toTeam&&drag.area===toArea?fromList:[...(to[toArea==='lineup'?'players':'bench'])];target.splice(toIndex,0,item);const fromUpdate={...from,[drag.area==='lineup'?'players':'bench']:fromList}; if(drag.team===toTeam) updateTeam(toTeam,{...fromUpdate,[toArea==='lineup'?'players':'bench']:target}); else {updateTeam(drag.team,fromUpdate);updateTeam(toTeam,{...to,[toArea==='lineup'?'players':'bench']:target})};setDrag(null)}
  const editPlayer=(which:'away'|'home',area:'lineup'|'bench',index:number,field:'name'|'pos',value:string)=>{const team=getTeam(which),key=area==='lineup'?'players':'bench', list=[...team[key]],player={...list[index]};if(field==='name'){const [last,first='']=value.trim().split(/\s+/);player.last=last||player.last;player.first=first}else player.pos=value;list[index]=player;updateTeam(which,{...team,[key]:list})}
  const positionPlayer=(source:string,target:string)=>{if(!admin)return;const team=home;const src=team.players.findIndex(p=>p.pos===source),dst=team.players.findIndex(p=>p.pos===target);if(src<0)return;const players=[...team.players];if(dst>=0){[players[src].pos,players[dst].pos]=[players[dst].pos,players[src].pos]}else players[src]={...players[src],pos:target};setHome({...team,players})}
  const dropOnField=(slot:string)=>{if(!drag||drag.team!=='home')return;if(drag.area==='lineup'){const source=home.players[drag.index];if(source)positionPlayer(source.pos,slot);setDrag(null);return}const benchPlayers=[...home.bench], [incoming]=benchPlayers.splice(drag.index,1);if(!incoming)return;const players=[...home.players], targetIndex=players.findIndex(p=>p.pos===slot);if(targetIndex>=0){const [outgoing]=players.splice(targetIndex,1);benchPlayers.push(outgoing)}players.push({...incoming,pos:slot});setHome({...home,players,bench:benchPlayers});setDrag(null)}
  const chooseDetailed=(pos:string)=>{const label=`${pos}${resultType}`;const bases=resultType==='安打'?1:resultType==='2塁打'?2:resultType==='3塁打'?3:0;if(bases)advanceHit(bases,label);else if(resultType==='ゴロ'||resultType==='飛'||resultType==='直')recordOut(label);setResultType(null)}
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-ball">●</span>草野球速報</div>{admin?<span className="admin-badge">管理者モード</span>:<button className="admin-open" onClick={()=>setAskPassword(true)}>管理者</button>}</header>
    <div className="game-meta"><span>練習試合</span><span>2026.09.14 多摩川グラウンド</span></div>
    <section className="scoreboard card"><div className="score-head"><span>第{inning}回{half}</span><strong>試合中</strong></div><div className="score-grid score-label"><span>TEAM</span>{[1,2,3,4,5].map(v=><span key={v}>{v}</span>)}<span>R</span></div><ScoreRow name={away.name} tone="away" scores={innings.away} total={awayScore}/><ScoreRow name={home.name} tone="home" scores={innings.home} total={homeScore}/></section>
    <section className="at-bat card"><div className="section-eyebrow">NOW BATTING</div><div className="players-row"><div className="player"><Avatar name={batter.last}/><div><small>{batterIndex+1}番 {batter.pos}</small><h2>{batter.last}</h2><p>打率 <b>{batter.avg}</b></p><p>5打数 2安打</p></div></div><div className="versus"><span>VS</span><small>対戦成績</small><b>2打数 1安打</b></div><div className="player pitcher"><Avatar name={pitcher.last}/><div><small>P</small><h2>{pitcher.last}</h2><p>防御率 <b>2.45</b></p><p>投球数 48</p></div></div></div><div className="count-row"><Count label="B" active={balls} max={3} tone="ball"/><Count label="S" active={strikes} max={2} tone="strike"/><Count label="O" active={outs} max={3} tone="out"/></div>{lastResult&&<div className="result-banner"><span>打席結果</span><strong>{lastResult}</strong></div>}</section>
    <section className="field-card card"><div className="section-title"><span>守備・出塁状況</span><small>{admin?'選手をドラッグして守備変更':'守備：府中フェニックス'}</small></div><div className="field"><div className="diamond"><i className="base base-2">{runners[2]&&<Runner name={runners[2]}/>}</i><i className="base base-3">{runners[3]&&<Runner name={runners[3]}/>}</i><i className="base base-1">{runners[1]&&<Runner name={runners[1]}/>}</i></div>{fieldSlots.map(slot=>{const p=home.players.find(v=>v.pos===slot);return <div className={`fielder ${slotToClass(slot)}`} key={slot} draggable={admin&&!!p} onDragStart={()=>p&&setDrag({team:'home',area:'lineup',index:home.players.indexOf(p)})} onDragOver={e=>admin&&e.preventDefault()} onDrop={()=>dropOnField(slot)} onClick={()=>admin&&p&&editPlayer('home','lineup',home.players.indexOf(p),'name',window.prompt('苗字 名前を入力',`${p.last} ${p.first}`)??`${p.last} ${p.first}`)}>{p?<><Avatar name={p.last} small/><span>{p.last}</span><em>{p.pos}</em></>:<span className="empty-slot">{slot}</span>}</div>})}</div></section>
    <Lineups away={away} home={home} admin={admin} drag={drag} onDrag={setDrag} onDrop={movePlayer} onEdit={editPlayer}/>
    <section className="history card"><div className="section-title"><span>試合経過</span><small>新しい順</small></div>{plays.length?plays.map((play,i)=><div className="play" key={`${play}-${i}`}><span>{play.split(' ')[0]}</span><b>{play.split(' ').slice(1).join(' ')}</b></div>):<p className="empty">まだ試合経過はありません</p>}</section>
    {admin&&<section className="admin card"><div className="admin-heading"><div><span className="section-eyebrow">ADMIN CONTROLS</span><h2>試合を更新</h2></div></div><p className="admin-current">第{inning}回{half} <span>{batterIndex+1}番 {batter.last}</span> の打席</p><div className="controls"><div className="control-group"><span>カウント</span><div><button onClick={()=>pitch('strike')}>ストライク</button><button onClick={()=>pitch('ball')}>ボール</button><button onClick={()=>pitch('foul')}>ファウル</button></div></div><div className="control-group"><span>打席結果</span><div>{['安打','2塁打','3塁打','HR','四球','三振','ゴロ','飛','直'].map(r=><button className={r==='HR'?'hr':''} key={r} onClick={()=>{if(['安打','2塁打','3塁打','ゴロ','飛','直'].includes(r))setResultType(r);else if(r==='HR')advanceHit(4,'ホームラン');else if(r==='四球')walk();else recordOut('三振')}}>{r}</button>)}</div></div>{resultType&&<div className="detail-picker"><span>{resultType}の打球位置</span>{positions.slice(0,9).map(pos=><button key={pos} onClick={()=>chooseDetailed(pos)}>{pos}</button>)}</div>}<div className="side-control"><button onClick={changeSide}>攻守交代</button><button className="reset" onClick={()=>{setInning(1);setHalf('表');setAwayScore(0);setHomeScore(0);setInnings({away:[0,null,null,null,null],home:[0,null,null,null,null]});setRunners({});setPlays([]);setOuts(0);resetCount()}}>試合をリセット</button></div></div></section>}
    {askPassword&&<div className="modal-backdrop"><form className="password-modal" onSubmit={e=>{e.preventDefault();submitPassword()}}><span className="section-eyebrow">ADMIN LOGIN</span><h2>管理者パスワード</h2><p>試合を操作するにはパスワードが必要です。</p><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="パスワードを入力"/><div>{passwordError&&<small className="error">パスワードが違います</small>}</div><button type="submit">管理者モードにする</button><button type="button" className="cancel" onClick={()=>setAskPassword(false)}>キャンセル</button></form></div>}
  </main>
}
function ScoreRow({name,tone,scores,total}:{name:string;tone:string;scores:(number|null)[];total:number}){return <div className="score-grid"><b className="team-name"><span className={`team-dot ${tone}`}/>{name}</b>{scores.map((v,i)=><span key={i}>{v??'－'}</span>)}<strong>{total}</strong></div>}
function Count({label,active,max,tone}:{label:string;active:number;max:number;tone:string}){return <div className="count"><b>{label}</b><span>{Array.from({length:max},(_,i)=><i className={i<active?tone:''} key={i}/>)}</span></div>}
function Runner({name}:{name:string}){return <span className="runner"><Avatar name={name} small/><b>{name}</b></span>}
function slotToClass(pos:string){return ({左:'lf',中:'cf',右:'rf',三:'third',遊:'ss',二:'second',一:'first',投:'pitcher',捕:'catcher'}as Record<string,string>)[pos]}
function Lineups({away,home,admin,drag,onDrag,onDrop,onEdit}:{away:Team;home:Team;admin:boolean;drag:{team:'away'|'home';area:'lineup'|'bench';index:number}|null;onDrag:(d:{team:'away'|'home';area:'lineup'|'bench';index:number})=>void;onDrop:(team:'away'|'home',area:'lineup'|'bench',index:number)=>void;onEdit:(team:'away'|'home',area:'lineup'|'bench',index:number,field:'name'|'pos',value:string)=>void}){return <section className="lineups card"><div className="section-title"><span>メンバー・打順</span><small>{admin?'ドラッグで打順・ベンチを変更できます':'両チームの打順'}</small></div><div className="lineup-head"><b>{away.name}</b><b>{home.name}</b></div><div className="lineup-columns"><LineupColumn team={away} id="away" admin={admin} drag={drag} onDrag={onDrag} onDrop={onDrop} onEdit={onEdit}/><LineupColumn team={home} id="home" admin={admin} drag={drag} onDrag={onDrag} onDrop={onDrop} onEdit={onEdit}/></div></section>}
type DragItem = { team: 'away' | 'home'; area: 'lineup' | 'bench'; index: number }
type LineupColumnProps = { team: Team; id: 'away' | 'home'; admin: boolean; drag: DragItem | null; onDrag: (item: DragItem) => void; onDrop: (team: 'away' | 'home', area: 'lineup' | 'bench', index: number) => void; onEdit: (team: 'away' | 'home', area: 'lineup' | 'bench', index: number, field: 'name' | 'pos', value: string) => void }
function LineupColumn({team,id,admin,drag,onDrag,onDrop,onEdit}:LineupColumnProps){const row=(p:Player,i:number,area:'lineup'|'bench')=><div className={`lineup-row ${drag?.team===id&&drag?.area===area&&drag?.index===i?'dragging':''}`} key={p.id} draggable={admin} onDragStart={()=>onDrag({team:id,area,index:i})} onDragOver={e=>admin&&e.preventDefault()} onDrop={()=>onDrop(id,area,i)}><span>{area==='lineup'?i+1:'・'}</span>{admin?<select value={p.pos} onChange={e=>onEdit(id,area,i,'pos',e.target.value)}>{positions.map(pos=><option key={pos}>{pos}</option>)}</select>:<b>{p.pos}</b>}{admin?<button onClick={()=>{const val=window.prompt('苗字 名前を入力',`${p.last} ${p.first}`);if(val)onEdit(id,area,i,'name',val)}}>{p.last} {p.first}</button>:<strong>{p.last} {p.first}</strong>}<em>{p.avg}</em></div>;return <div className="team-lineup">{team.players.map((p,i)=>row(p,i,'lineup'))}<div className="bench-label">ベンチ</div><div className="bench" onDragOver={e=>admin&&e.preventDefault()} onDrop={()=>onDrop(id,'bench',team.bench.length)}>{team.bench.map((p,i)=>row(p,i,'bench'))}{admin&&<small>ここへドロップ</small>}</div></div>}
export default App
